oss:
  type: ali
  prefix: k-File
  endpoint: oss-cn-beijing.aliyuncs.com
  internalEndpoint: oss-cn-beijing-internal.aliyuncs.com
  ak: ${OSS_AK}
  sk: ${OSS_SK}
  bucket: oss-kk
  host: https://oss-kk.oss-cn-beijing.aliyuncs.com/

spring:
  profiles:
    active: dev
  config:
    import: application-${spring.profiles.active}.yml

geoip:
  enabled: ${GEOIP_ENABLED:false}
  mmdbPath: ${GEOIP_MMDB_PATH:}
